# Room settings
ROOM_PARTY_CAPACITY = 9

# Dormitory settings
NUM_FLOORS = 5
ROOMS_PER_FLOOR = 8

#Students JSON directory
POPULATION_DIRECTORY = 'population_data/'

SELECTED_POPULATION_CATALOG = 'the_office/'
POPULATION_FILE_NAME = 'student_data.json'

POPULATION_FILE = POPULATION_DIRECTORY + SELECTED_POPULATION_CATALOG + POPULATION_FILE_NAME
POPULATION_ASSETS_DIRECTORY = POPULATION_DIRECTORY + SELECTED_POPULATION_CATALOG  + 'assets/'